export type Language = 'en' | 'tr';

export const en = {
  seo: { title: 'VELNAR | Software Intelligence & Verification', description: 'VELNAR is building a Software Intelligence & Verification Platform that combines deterministic software analysis with evidence-bound verification architecture, starting with application security.' },
  skip: 'Skip to content', menu: 'Menu', close: 'Close menu', language: 'Language',
  nav: ['Platform', 'Architecture', 'Maturity', 'Markets', 'Vision', 'Pilot Access'],
  primary: 'Request Pilot Access', secondary: 'Explore the Architecture',
  hero: { eyebrow: 'Software Intelligence & Verification', line1: 'From security findings to', line2: 'evidence-backed decisions.', description: 'VELNAR is building a Software Intelligence & Verification Platform that combines deterministic software analysis with evidence-bound verification architecture, starting with application security.', wedge: 'Starting with application security', status: 'Engineering foundation · In development', figure: 'An evidence-first architecture', candidate: 'Finding Candidate', boundary: 'Verification boundary', evidence: 'Verified Finding', note: 'AI can propose. Evidence must prove.', figureLabel: 'Fulgor · independent verification layer under development' },
  problem: { eyebrow: '01 / The problem', title: 'Security tools find issues.', highlight: 'Teams still have to decide which ones are real.', description: 'A finding is the beginning of an investigation. Teams need context and evidence before they can decide what deserves action.', items: [
    { title: 'Too many alerts', body: 'A growing queue competes with the work that actually reduces risk.' },
    { title: 'Unclear reachability', body: 'A suspicious code path does not establish whether an issue can be reached.' },
    { title: 'Risk without context', body: 'A theoretical weakness and a meaningful application risk are different questions.' },
    { title: 'Triage falls to developers', body: 'Engineers reconstruct context, check assumptions, and decide what to fix.' }
  ] },
  workflow: { eyebrow: '02 / Platform architecture', title: 'From understanding to controlled action.', description: 'Five connected stages with visibly different maturity. A proposed finding and a verified finding remain separated by an explicit evidence boundary.', current: 'Current foundation', proving: 'Architecture · Under development', roadmap: 'Roadmap', stages: [
    { verb: 'Understand', title: 'Software Intelligence', body: 'Build structured context from software. The current foundation covers a bounded TypeScript/Express subset.' },
    { verb: 'Detect', title: 'Deterministic Analysis', body: 'Deterministic SQLi detection is the current foundation. AI may later assist analysis but cannot grant verification authority.' },
    { verb: 'Verify', title: 'Fulgor Verification', body: 'An independent verification layer under development, designed to test candidates against evidence requirements.' },
    { verb: 'Remember', title: 'Security Memory', body: 'Roadmap architecture for retaining software context, provenance, and evidence.' },
    { verb: 'Act', title: 'Controlled Action', body: 'Roadmap architecture for action within human and policy boundaries.' }
  ] },
  trust: { eyebrow: '03 / Evidence & authority', title: 'AI can propose.', highlight: 'Evidence must prove.', description: 'An AI model cannot directly grant VERIFIED authority. A Finding Candidate must cross a controlled verification boundary; authority depends on validated evidence and explicit state transitions.', flow: ['Source Code', 'Structured Analysis', 'Finding Candidate', 'Verification Boundary', 'Evidence', 'Trusted State'], distinction: 'Finding Candidate ≠ Verified Finding', caption: 'Conceptual authority flow. Contracts and validation foundations exist; end-to-end independent verification remains under development.', rules: [
    { title: 'Bound to the code', body: 'Repository and code-state binding keeps evidence tied to the exact software state it describes.' },
    { title: 'Traceable provenance', body: 'Evidence needs an identifiable origin and a record of how it was produced.' },
    { title: 'Deterministic validation', body: 'Strict contracts and validation constrain what can enter an authoritative state.' },
    { title: 'Controlled authority', body: 'State transitions follow explicit rules, with human and policy authority over consequential action.' }
  ] },
  capability: { eyebrow: '04 / Capability maturity', title: 'Built foundations.', highlight: 'A staged path to proof and scale.', description: 'The product story separates implemented engineering, the next proof work, and longer-term platform expansion.', levels: [
    { label: 'BUILT TODAY', title: 'Inspectable foundations', body: 'Implemented within a controlled engineering scope.', items: ['M0/M1 · Canonical Security Contracts, evidence/state authority foundation, strict validation', 'M2 · Executable benchmark foundation with 8 controlled TypeScript/Express SQL injection scenarios', 'M3 · Deterministic SQLi detection foundation for a bounded TypeScript/Express subset'] },
    { label: 'PROVING NEXT', title: 'Evidence from real use', body: 'The next phase measures performance and develops verification with partners.', items: ['Real repository benchmarks', 'Precision / recall and TP / FP / FN measurement', 'Design partners and Controlled PoV', 'Continued Fulgor development as an independent verification layer under development'] },
    { label: 'SCALING LATER', title: 'Platform expansion', body: 'Roadmap directions after the next proof phase.', items: ['Broader language, framework, and vulnerability-class coverage', 'Security Memory and Controlled Action', 'Enterprise, private, and sovereign deployment', 'Partner and embedded distribution', 'High-trust and defense-adjacent architecture'] }
  ] },
  engineering: { eyebrow: '05 / Technical evidence', title: 'Engineering Evidence', description: 'A compact record of the current internal regression baseline.', regression: 'Current regression baseline', metrics: ['M3 tests', 'M2 tests', 'Intelligence tests', 'Full tests'], disclaimer: 'Internal engineering regression results. Not production accuracy metrics.', limits: 'These passing tests do not establish real-world accuracy, precision, recall, false-positive rate, broad language coverage, or production readiness.' },
  audience: { eyebrow: '06 / Market expansion', title: 'Focused market entry.', highlight: 'Broad software-economy applicability.', description: 'Design-partner and early Controlled PoV work begins with software-heavy technology companies, followed by staged expansion.', groups: [
    { stage: 'INITIAL WEDGE', title: 'Software-heavy technology companies', body: 'Where design-partner and early Controlled PoV work begins.', items: ['SaaS', 'AI-native products', 'API companies', 'Developer platforms', 'High-growth engineering teams'] },
    { stage: 'BROADER SOFTWARE-DEPENDENT BUSINESSES', title: 'Organizations built on software', body: 'Future applicability across businesses operating important websites, APIs, applications, and software systems.', items: ['E-commerce', 'Fintech', 'Health-tech', 'Logistics', 'Travel', 'Education technology', 'Mobile-app companies', 'Online platforms'] },
    { stage: 'ENTERPRISE & HIGH-TRUST', title: 'Enterprise and regulated environments', body: 'Future expansion for organizations with demanding assurance requirements.', items: ['Large technology companies', 'Financial organizations', 'Telecom', 'Regulated businesses', 'High-trust software environments'] },
    { stage: 'PARTNERS & PLATFORMS', title: 'Distribution through the ecosystem', body: 'Future partner and platform distribution.', items: ['MSSPs', 'Security providers', 'Software agencies', 'Cloud and hosting providers', 'Developer platforms', 'CI/CD ecosystems', 'Platform integrations', 'Embedded VELNAR'] }
  ] },
  business: { eyebrow: '07 / Business model', title: 'Three commercial layers.', description: 'VELNAR begins with a focused cloud product and keeps enterprise and platform expansion clearly staged. Future channels are not active offerings today.', layers: [
    { badge: 'INITIAL COMMERCIAL PRODUCT', title: 'VELNAR CLOUD', body: 'The first commercial product for software and security teams.', items: ['Team subscription', 'Design-partner / Controlled PoV workflow', 'Software and security team workspace'] },
    { badge: 'FUTURE EXPANSION', title: 'VELNAR ENTERPRISE', body: 'Planned deployment and contracting options for organizational boundaries.', items: ['Annual enterprise contracts', 'Private deployment', 'On-premise deployment', 'Regulated and sovereign deployment'] },
    { badge: 'PLANNED PLATFORM EXPANSION', title: 'VELNAR PLATFORM', body: 'Planned verification and distribution surfaces.', items: ['Fulgor Verification · independent verification layer under development', 'VELNAR API / SDK', 'VELNAR Partner', 'Embedded VELNAR'] }
  ] },
  critical: { eyebrow: '08 / Strategic expansion', title: 'Higher-trust environments are a strategic expansion.', description: 'VELNAR’s evidence-first architecture is being designed with the long-term requirements of regulated, sovereign and security-critical software environments in mind.', label: 'Future architectural directions may include', capabilities: ['Private and on-premise deployment', 'Air-gapped environments', 'Software supply-chain assurance', 'Sovereign data and model boundaries', 'Machine-checkable security evidence'], environmentLabel: 'Potential future environments', environments: ['Defense', 'Aerospace', 'Financial infrastructure', 'Telecom', 'Critical infrastructure'], maturity: 'Strategic expansion. No current defense product, customer, deployment, or production-defense readiness is claimed.' },
  vision: { eyebrow: '09 / Global vision', title: 'Designed from the start for international software teams, enterprise environments and platform-scale distribution.', description: 'The product and delivery roadmap anticipates different organizational, regional, and integration boundaries.', items: ['International software-team workflows', 'Enterprise and private deployment options later', 'Platform and embedded distribution', 'Regional and sovereign boundaries later', 'API and ecosystem integration', 'International security standards roadmap'], conclusion1: 'The engineering foundation begins with a bounded application-security scope.', conclusion2: 'The long-term architecture is intended to support international, enterprise, and platform-scale use.' },
  partner: { eyebrow: '10 / Build with us', title: 'VELNAR Design Partner Program', description: 'Help shape the next proof phase through a controlled early product-development program.', detail: 'For software and AI teams interested in real repository benchmarks, evaluation criteria, and a Controlled Proof of Value. Scope and participation will be discussed individually.', cta: 'Request Pilot Access', emailLabel: 'Contact the team', note: 'Tell us about your team and the problem you want to evaluate. Do not include repository source code, credentials, or secrets.', fields: ['Name', 'Work email', 'Company', 'Role', 'Company type', 'Engineering team size', 'Message'], types: ['Software-heavy technology company', 'Software-dependent business', 'Enterprise / regulated organization', 'Partner / platform', 'Other'], sizes: ['1–10', '11–50', '51–200', '201–500', '500+', 'Prefer not to say'], select: 'Select an option', optional: 'Optional', required: 'Name, work email, and company are required.', prepare: 'Prepare email draft', draftTitle: 'Your email draft is ready.', draftNote: 'Nothing has been submitted. Open your email app to review and send, or copy the draft and email it to', open: 'Open email app', copy: 'Copy draft', copied: 'Draft copied.', copyFailed: 'Copy is unavailable. Select and copy the draft below.', edit: 'Edit details', draftLabel: 'Email draft', noScript: 'Enable JavaScript to prepare a draft, or contact us directly by email.', privacy: 'This form prepares an email on your device. It does not submit or store your details on this website.', invalid: 'Please enter a value containing more than spaces.', subject: 'VELNAR pilot access request' },
  privacy: { title: 'Privacy & contact', body: 'The pilot-access form keeps your entries in page memory while you prepare a draft. It does not send them to a website backend or save them in browser storage. Opening an email draft hands the details to your email app; sending is your decision. For questions about information you choose to email, or to request an update or deletion, contact', caution: 'Please share business context only. Do not send source code, credentials, or confidential system details through this form.' },
  footer: { lines: ['Software Intelligence.', 'Verification.', 'Controlled Action.'], links: ['Platform', 'Security / Trust', 'Pilot Access', 'Contact', 'Privacy'], note: 'Engineering foundation in development.' },
  retired: { title: 'This page is no longer available.', body: 'Explore VELNAR’s software intelligence and verification platform.', cta: 'Go to VELNAR' }
};
export type Copy = typeof en;
