import type { Copy } from './en';

export const tr: Copy = {
  seo: { title: 'VELNAR | Yazılım Zekâsı ve Doğrulama', description: 'VELNAR, uygulama güvenliğinden başlayarak deterministik yazılım analizini kanıta bağlı doğrulama mimarisiyle birleştiren bir Yazılım Zekâsı ve Doğrulama Platformu geliştiriyor.' },
  skip: 'İçeriğe geç', menu: 'Menü', close: 'Menüyü kapat', language: 'Dil',
  nav: ['Platform', 'Mimari', 'Olgunluk', 'Pazarlar', 'Vizyon', 'Pilot Erişim'],
  primary: 'Pilot Erişim Talep Edin', secondary: 'Mimariyi İnceleyin',
  hero: { eyebrow: 'Yazılım Zekâsı ve Doğrulama', line1: 'Güvenlik bulgularından', line2: 'kanıta dayalı kararlara.', description: 'VELNAR, uygulama güvenliğinden başlayarak deterministik yazılım analizini kanıta bağlı doğrulama mimarisiyle birleştiren bir Yazılım Zekâsı ve Doğrulama Platformu geliştiriyor.', wedge: 'İlk odak: uygulama güvenliği', status: 'Mühendislik temeli · Geliştirme aşamasında', figure: 'Kanıtı esas alan mimari', candidate: 'Bulgu Adayı', boundary: 'Doğrulama sınırı', evidence: 'Doğrulanmış Bulgu', note: 'Yapay zekâ önerebilir. Kanıt doğrulamalıdır.', figureLabel: 'Fulgor · geliştirilmekte olan bağımsız doğrulama katmanı' },
  problem: { eyebrow: '01 / Sorun', title: 'Güvenlik araçları sorun bulur.', highlight: 'Hangilerinin gerçek olduğuna karar vermek hâlâ ekiplere düşer.', description: 'Bir bulgu, incelemenin başlangıcıdır. Ekiplerin neye müdahale edeceklerini belirlemek için bağlama ve kanıta ihtiyacı vardır.', items: [
    { title: 'Uyarı yükü', body: 'Büyüyen uyarı kuyruğu, riski gerçekten azaltacak işlerin önüne geçer.' },
    { title: 'Erişilebilirlik belirsizliği', body: 'Şüpheli bir kod yolu, o soruna uygulamada gerçekten ulaşılabildiğini göstermez.' },
    { title: 'Bağlamdan kopuk risk', body: 'Teorik bir zayıflık ile uygulama açısından anlamlı bir risk aynı şey değildir.' },
    { title: 'İnceleme yükü geliştiricide', body: 'Mühendisler bağlamı yeniden kurar, varsayımları kontrol eder ve neyin düzeltilmesi gerektiğine karar verir.' }
  ] },
  workflow: { eyebrow: '02 / Platform mimarisi', title: 'Yazılımı anlamaktan kontrollü aksiyona.', description: 'Olgunluk düzeyleri açıkça ayrılmış beş bağlantılı aşama. Önerilen bulgu ile doğrulanmış bulgu arasında kanıta dayalı açık bir sınır bulunur.', current: 'Mevcut temel', proving: 'Mimari · Geliştirme aşamasında', roadmap: 'Yol haritası', stages: [
    { verb: 'Anla', title: 'Yazılım Zekâsı', body: 'Yazılımdan yapılandırılmış bağlam çıkarır. Mevcut temel, TypeScript/Express’in sınırlı bir alt kümesini kapsar.' },
    { verb: 'Tespit Et', title: 'Deterministik Analiz', body: 'Mevcut temel, deterministik SQL enjeksiyonu tespitidir. Yapay zekâ ileride analize yardımcı olabilir, ancak doğrulama yetkisi veremez.' },
    { verb: 'Doğrula', title: 'Fulgor Verification', body: 'Adayları kanıt gereksinimleriyle sınamak üzere geliştirilmekte olan bağımsız doğrulama katmanı.' },
    { verb: 'Hatırla', title: 'Güvenlik Belleği', body: 'Yazılım bağlamını, kanıtın kökenini ve geçmişini korumaya yönelik yol haritası mimarisi.' },
    { verb: 'Harekete Geç', title: 'Kontrollü Aksiyon', body: 'İnsan ve politika sınırları içinde aksiyona yönelik yol haritası mimarisi.' }
  ] },
  trust: { eyebrow: '03 / Kanıt ve yetki', title: 'Yapay zekâ önerebilir.', highlight: 'Kanıt doğrulamalıdır.', description: 'Bir yapay zekâ modeli doğrudan VERIFIED (doğrulanmış) yetkisi veremez. Bulgu Adayı kontrollü bir doğrulama sınırını geçmelidir; yetki, geçerli kanıta ve açık durum geçişlerine bağlıdır.', flow: ['Kaynak Kod', 'Yapılandırılmış Analiz', 'Bulgu Adayı', 'Doğrulama Sınırı', 'Kanıt', 'Güvenilir Durum'], distinction: 'Bulgu Adayı ≠ Doğrulanmış Bulgu', caption: 'Kavramsal yetki akışı. Sözleşmelerin ve geçerlilik kontrollerinin temeli mevcut; uçtan uca bağımsız doğrulama geliştirme aşamasında.', rules: [
    { title: 'Kod durumuna bağlı', body: 'Depo ve kod sürümüyle kurulan bağ, kanıtın tam olarak hangi yazılım durumunu anlattığını korur.' },
    { title: 'İzlenebilir kanıt kökeni', body: 'Kanıtın kaynağı ve nasıl üretildiği kayıt altına alınabilir ve takip edilebilir olmalıdır.' },
    { title: 'Deterministik geçerlilik kontrolü', body: 'Katı sözleşmeler ve kontroller, hangi verinin yetkili bir duruma geçebileceğini sınırlar.' },
    { title: 'Kontrollü yetki', body: 'Durum geçişleri açık kurallara uyar. Sonuç doğuran aksiyonlar insan ve politika yetkisine tabidir.' }
  ] },
  capability: { eyebrow: '04 / Yetenek olgunluğu', title: 'İnşa edilen temel.', highlight: 'Kanıtlama ve ölçeklenme için aşamalı yol.', description: 'Ürün anlatısı; uygulanmış mühendisliği, sıradaki kanıtlama işlerini ve uzun vadeli platform genişlemesini birbirinden ayırır.', levels: [
    { label: 'BUGÜN İNŞA EDİLEN', title: 'İncelenebilir temeller', body: 'Kontrollü bir mühendislik kapsamında uygulanmıştır.', items: ['M0/M1 · Kanonik Güvenlik Sözleşmeleri, kanıt/durum yetkisi temeli ve katı geçerlilik kontrolleri', 'M2 · 8 kontrollü TypeScript/Express SQL enjeksiyonu senaryosuna sahip çalıştırılabilir kıyaslama temeli', 'M3 · TypeScript/Express’in sınırlı bir alt kümesi için deterministik SQLi tespit temeli'] },
    { label: 'SIRADAKİ KANITLAMA AŞAMASI', title: 'Gerçek kullanımdan kanıt', body: 'Sıradaki aşama performansı ölçer ve doğrulamayı iş ortaklarıyla geliştirir.', items: ['Gerçek depo kıyaslamaları', 'Kesinlik / duyarlılık ile TP / FP / FN ölçümü', 'VELNAR Design Partner Programı ve Kontrollü PoV', 'Geliştirilmekte olan bağımsız doğrulama katmanı olarak Fulgor çalışmalarının sürdürülmesi'] },
    { label: 'ÖLÇEKLENME MİMARİSİ', title: 'Platform genişlemesi', body: 'Sıradaki kanıtlama aşamasından sonraki yol haritası yönleri.', items: ['Daha geniş dil, framework ve güvenlik açığı sınıfı kapsamı', 'Güvenlik Belleği ve Kontrollü Aksiyon', 'Kurumsal, özel ve egemen kurulum', 'İş ortağı ve gömülü dağıtım', 'Yüksek güven ve savunma bağlantılı mimari'] }
  ] },
  engineering: { eyebrow: '05 / Teknik kanıt', title: 'Mühendislik Kanıtları', description: 'Mevcut dahili regresyon temelinin kısa bir kaydı.', regression: 'Mevcut regresyon temeli', metrics: ['M3 testleri', 'M2 testleri', 'Yazılım zekâsı testleri', 'Tüm testler'], disclaimer: 'Dahili mühendislik regresyon sonuçlarıdır. Üretim ortamı doğruluk metrikleri değildir.', limits: 'Bu başarılı testler; gerçek dünya doğruluğunu, kesinliği, duyarlılığı, yanlış pozitif oranını, geniş dil kapsamını veya üretime hazır olmayı kanıtlamaz.' },
  audience: { eyebrow: '06 / Pazar genişlemesi', title: 'Odaklı pazara giriş.', highlight: 'Yazılım ekonomisinin geneline uzanan potansiyel.', description: 'VELNAR Design Partner Programı ve ilk Kontrollü PoV çalışmaları, yazılım yoğun teknoloji şirketleriyle başlar; ardından aşamalı genişleme gelir.', groups: [
    { stage: 'İLK PAZARA GİRİŞ', title: 'Yazılım yoğun teknoloji şirketleri', body: 'VELNAR Design Partner Programı ve ilk Kontrollü PoV çalışmalarının başladığı alan.', items: ['SaaS', 'Yapay zekâ odaklı ürünler', 'API şirketleri', 'Geliştirici platformları', 'Hızla büyüyen mühendislik ekipleri'] },
    { stage: 'YAZILIMA BAĞIMLI İŞLETMELER', title: 'Yazılım üzerinde çalışan işletmeler', body: 'Önemli web siteleri, API’ler, uygulamalar ve yazılım sistemleri işleten kurumlara gelecekteki uygulanabilirlik.', items: ['E-ticaret', 'Fintech', 'Sağlık teknolojileri', 'Lojistik', 'Seyahat', 'Eğitim teknolojileri', 'Mobil uygulama şirketleri', 'Çevrimiçi platformlar'] },
    { stage: 'KURUMSAL VE YÜKSEK GÜVEN', title: 'Kurumsal ve regüle ortamlar', body: 'Yüksek güvence gereksinimleri olan kurumlara yönelik gelecek genişlemesi.', items: ['Büyük teknoloji şirketleri', 'Finans kuruluşları', 'Telekom', 'Regüle işletmeler', 'Yüksek güven gerektiren yazılım ortamları'] },
    { stage: 'İŞ ORTAKLARI VE PLATFORMLAR', title: 'Ekosistem üzerinden dağıtım', body: 'Gelecekteki iş ortağı ve platform dağıtımı.', items: ['MSSP’ler', 'Güvenlik sağlayıcıları', 'Yazılım ajansları', 'Bulut ve barındırma sağlayıcıları', 'Geliştirici platformları', 'CI/CD ekosistemleri', 'Platform entegrasyonları', 'Embedded VELNAR'] }
  ] },
  business: { eyebrow: '07 / İş modeli', title: 'Üç ticari katman.', description: 'VELNAR, odaklı bir bulut ürünüyle başlar; kurumsal ve platform genişlemesini aşamalı biçimde konumlandırır. Gelecekteki kanallar bugün aktif ürünler değildir.', layers: [
    { badge: 'İLK TİCARİ ÜRÜN', title: 'VELNAR CLOUD', body: 'Yazılım ve güvenlik ekiplerine yönelik ilk ticari ürün.', items: ['Ekip aboneliği', 'VELNAR Design Partner Programı / Kontrollü PoV iş akışı', 'Yazılım ve güvenlik ekibi çalışma alanı'] },
    { badge: 'GELECEKTEKİ GENİŞLEME', title: 'VELNAR ENTERPRISE', body: 'Kurumsal sınırlar için planlanan kurulum ve sözleşme seçenekleri.', items: ['Yıllık kurumsal sözleşmeler', 'Özel kurulum', 'Kurum içi kurulum', 'Regüle ve egemen kurulum'] },
    { badge: 'PLANLANAN PLATFORM GENİŞLEMESİ', title: 'VELNAR PLATFORM', body: 'Planlanan doğrulama ve dağıtım yüzeyleri.', items: ['Fulgor Verification · geliştirilmekte olan bağımsız doğrulama katmanı', 'VELNAR API / SDK', 'VELNAR Partner', 'Embedded VELNAR'] }
  ] },
  critical: { eyebrow: '08 / Stratejik genişleme', title: 'Yüksek güven gerektiren ortamlar stratejik bir genişleme alanıdır.', description: 'VELNAR’ın kanıt öncelikli mimarisi; uzun vadede regüle, veri egemenliği gerektiren ve güvenlik açısından kritik yazılım ortamlarının ihtiyaçları gözetilerek geliştirilmektedir.', label: 'Gelecekteki mimari yönler', capabilities: ['Özel ve kurum içi kurulum', 'Dış ağlardan yalıtılmış ortamlar', 'Yazılım tedarik zinciri güvencesi', 'Egemen veri ve model sınırları', 'Makineyle denetlenebilir güvenlik kanıtı'], environmentLabel: 'Gelecekte değerlendirilebilecek ortamlar', environments: ['Savunma', 'Havacılık ve uzay', 'Finansal altyapı', 'Telekom', 'Kritik altyapı'], maturity: 'Stratejik genişleme. Mevcut savunma ürünü, müşterisi, kurulumu veya savunma alanında üretime hazır olma iddiası yoktur.' },
  vision: { eyebrow: '09 / Küresel vizyon', title: 'Baştan itibaren uluslararası yazılım ekipleri, kurumsal ortamlar ve platform ölçeğinde dağıtım için tasarlanıyor.', description: 'Ürün ve dağıtım yol haritası farklı kurumsal, bölgesel ve entegrasyon sınırlarını gözetir.', items: ['Uluslararası yazılım ekibi iş akışları', 'İleride kurumsal ve özel kurulum seçenekleri', 'Platform ve gömülü dağıtım', 'İleride bölgesel ve egemen sınırlar', 'API ve ekosistem entegrasyonu', 'Uluslararası güvenlik standartları yol haritası'], conclusion1: 'Mühendislik temeli, sınırları belli bir uygulama güvenliği kapsamıyla başlıyor.', conclusion2: 'Uzun vadeli mimari uluslararası, kurumsal ve platform ölçeğindeki kullanımı desteklemek üzere tasarlanıyor.' },
  partner: { eyebrow: '10 / Birlikte geliştirelim', title: 'VELNAR Design Partner Programı', description: 'Erken Ürün Geliştirme Programı ile sıradaki kanıtlama aşamasını birlikte şekillendirin.', detail: 'Gerçek depo kıyaslamaları, değerlendirme ölçütleri ve Kontrollü Değer Kanıtlama çalışmalarıyla ilgilenen yazılım ve yapay zekâ ekipleri için. Kapsam ve katılım her ekiple ayrı görüşülecektir.', cta: 'Pilot Erişim Talep Edin', emailLabel: 'Ekiple iletişime geçin', note: 'Ekibinizi ve değerlendirmek istediğiniz sorunu anlatın. Depo kaynak kodu, erişim bilgileri veya sırlar paylaşmayın.', fields: ['Ad soyad', 'İş e-postası', 'Şirket', 'Görev', 'Şirket türü', 'Mühendislik ekibi büyüklüğü', 'Mesaj'], types: ['Yazılım yoğun teknoloji şirketi', 'Yazılıma bağımlı işletme', 'Kurumsal / regüle organizasyon', 'İş ortağı / platform', 'Diğer'], sizes: ['1–10', '11–50', '51–200', '201–500', '500+', 'Belirtmek istemiyorum'], select: 'Bir seçenek seçin', optional: 'İsteğe bağlı', required: 'Ad soyad, iş e-postası ve şirket alanları zorunludur.', prepare: 'E-posta taslağı hazırla', draftTitle: 'E-posta taslağınız hazır.', draftNote: 'Henüz hiçbir bilgi gönderilmedi. İnceleyip göndermek için e-posta uygulamanızı açın veya taslağı kopyalayıp şu adrese iletin:', open: 'E-posta uygulamasını aç', copy: 'Taslağı kopyala', copied: 'Taslak kopyalandı.', copyFailed: 'Kopyalama kullanılamıyor. Aşağıdaki taslağı seçip kopyalayabilirsiniz.', edit: 'Bilgileri düzenle', draftLabel: 'E-posta taslağı', noScript: 'Taslak hazırlamak için JavaScript’i etkinleştirin veya doğrudan e-postayla iletişime geçin.', privacy: 'Bu form cihazınızda bir e-posta taslağı hazırlar. Bilgilerinizi bu web sitesine göndermez veya kaydetmez.', invalid: 'Lütfen yalnızca boşluk içermeyen bir değer girin.', subject: 'VELNAR pilot erişim talebi' },
  privacy: { title: 'Gizlilik ve iletişim', body: 'Pilot erişim formundaki bilgiler, taslağı hazırlarken sayfa belleğinde tutulur. Bir web sunucusuna gönderilmez veya tarayıcı depolamasına kaydedilmez. E-posta taslağını açtığınızda bilgiler e-posta uygulamanıza aktarılır; gönderme kararı size aittir. E-postayla paylaşmayı seçtiğiniz bilgiler hakkında sorularınız, güncelleme veya silme talepleriniz için iletişim:', caution: 'Lütfen yalnızca iş bağlamını paylaşın. Bu form üzerinden kaynak kodu, erişim bilgisi veya gizli sistem ayrıntıları göndermeyin.' },
  footer: { lines: ['Yazılım Zekâsı.', 'Doğrulama.', 'Kontrollü Aksiyon.'], links: ['Platform', 'Güvenlik / Güven', 'Pilot Erişim', 'İletişim', 'Gizlilik'], note: 'Mühendislik temeli geliştirme aşamasında.' },
  retired: { title: 'Bu sayfa artık kullanılamıyor.', body: 'VELNAR’ın yazılım zekâsı ve doğrulama platformunu keşfedin.', cta: 'VELNAR’a gidin' }
};
